export const workersData= ['Name: Zuhra, salary: 511$, pets: dog',
'Name: Pastila Manson, salary: 381$, pets: none',
'Name: Nicol Dalas, salary: 566$, pets: hamster dog',
'Name: Pastila, salary: 407$, pets: parrot',
'Name: Samon Makee, salary: 213$, pets: dog parrot',
'Name: Margara Dalas, salary: 418€, pets: dog',
'Name: Franclin Manson, salary: 524€, pets: cat cat',
'Name: Corbin, salary: 197$, pets: none',
'Name: Sandra, salary: 587₽, pets: none',
'Name: Franclin, salary: 192€, pets: hamster',
'Name: Micle Cree, salary: 81£, pets: cat dog',
'Name: MultiPasport, salary: 406₽, pets: cat cat',
'Name: MultiPasport Lom, salary: 197$, pets: dog',
'Name: Margara Manson, salary: 76₽, pets: hamster parrot',
'Name: Zuhra Makee, salary: 216€, pets: none',
'Name: Markus, salary: 153₽, pets: none',
'Name: MultiPasport Makee, salary: 439$, pets: none',
'Name: Corbin Dalas, salary: 580$, pets: hamster',
'Name: Corbin Manson, salary: 490₽, pets: parrot',
'Name: MultiPasport, salary: 213₽, pets: hamster']